---

- name: Set correct nfs daemon name
  set_fact: nfs_server_daemon="nfs-server"

- name: Apply nfs service to public firewall zone
  firewalld: zone=public service=nfs permanent=true state=enabled immediate=true
  notify: 
  - reload firewalld
  - restart nfs
  tags:
  - nfs
