---
- name: Ensure NFS utilities are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - nfs-common
    - nfs-kernel-server

- name: Set correct nfs daemon name
  set_fact: nfs_server_daemon="nfs-kernel-server"
